[package]
name = "chippy-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
wrapping_arithmetic = "0.1.0"
# dynasmrt = "1.2.3"
dynasmrt = "1.2.1"
once_cell = "1.15.0"